name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          
      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --quiet
          php -r "unlink('composer-setup.php'); 

      - name: Install dependencies
        run: php composer.phar install --no-interaction --no-progress --prefer-dist

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Run linter
        run: vendor/bin/phpcs --standard=PSR12 app

      - name: Build assets (optional)
        run: npm install && npm run production
